---
title: "Training"
---

## Introduction

We will introduce ourselves to each other and then begin with the following video and discussion:

[The River Is Our Relative: The Story of the Penobscot Nation](https://www.youtube.com/watch?v=8VCr_bohahw) 

- What is the difference (in legal definitions and implications) between environmental justice and Tribal rights/trust responsibility?
- Environmental justice involves citizen science groups or communities that do not have sovereign status
- Penobscot Nation works with the federal government.
- See paper by Ranco and Suagee (2007) below to learn more about this

## About our Tribal partners: How did this collaboration come to be?

(Note: The following background material is quoted directly from the TXG website linked below.)

The Tribal Exchange Network Group ([TXG](https://www.tribalexchangenetwork.org/)) is a USEPA Tribal Partnership Group that is focused on building Tribal capacity through education, innovation, and information exchange. TXG's mission is to support Tribal management, analysis, and sharing of environmental data, so that it can be used to advocate for tribal interests, preserve tribal lifeways, maintain cultural integrity, and enhance tribal member's sense of place.

TXG is comprised of Tribal professionals experienced with managing, sharing, and analyzing environmental data. From Data Technicians to Environmental Directors, from coding geeks to grant writers, and from air, to water, to brownfields and beyond, TXG members have experience in all aspects of environmental data management.

As part of their mission, TXG members and collaborators already provide many great free resources to Tribal environmental professionals, including coding/data workshops, [drop-in office hours](https://www.tribalexchangenetwork.org/trainings-events), and one-on-one consulting. They are constantly looking for new resources and opportunities for capacity building for the Tribes. So this summer we are joining and supporting the great work that TXG and the Tribes are already doing.

Our main contact for this project is [Angie Reed](https://www.tribalexchangenetwork.org/angie-reed), Vice President of TXG and Water Resource Planner for the Penobscot Indian Nation. She has been a part of TXG since 2007. Her focus is to develop and facilitate the exchange of technical skills (e.g. in R and python) that make the daily lives of Tribal environmental professionals easier.



## Our work this summer

See our [schedule here](https://docs.google.com/spreadsheets/d/1up7SQiZ2mWkHVwk3W5fgH3nx_kHkNd0De2PPVhxNMFk/edit?usp=sharing) (internal link only)

- Join monthly Tribal data drop-ins

- Develop and lead monthly lessons for these drop-in sessions to provide ongoing support around R/R Studio and python (intro, graphs, for-loops, etc.)

- Join monthly PNW Tribal coding group meetings

- Attend and support a TXG/Data Carpentry python workshop

- Collaborate with Angie Reed and TXG to develop a suite of R workshop lessons tailored to Tribal data examples

- (Optional) Attend TXG conference this fall to connect in person with Tribal partners there




## Training to work constructively with Tribal partners

We will participate together in ongoing training beyond our initial training so that we can continue to learn about the following:

- Different roles and identities, such as tribal professionals vs tribal citizens

- Commonalities and differences in the history and current experience of Tribes across the nation

- Sensitivity of Tribal data and historical context for the importance of building trust

- The significance of the Boldt Decision for Pacific NW Tribes

- Tribal sovereignty and related legal issues that Tribes and Tribal environmental professionals deal with

- How to work respectfully and productively with Tribal partners




## Expectations

Together we will construct and agree to a short contract to summarize the standards for our work together.  Here are some draft ideas:

- We are collaborators and this is a mutual learning experience, an exchange. We will provide our skills and time to help Tribes build their capacity and resources, and we will learn skills from Tribal partners, build new relationships, and deepend our understanding of Tribal issues and environmental work.

- First and foremost, we are building relationships. We are not arriving, evaluating, deciding how to "help", taking action, and leaving. Instead of saying "I'm here to help you", we will ask, "What do you need?"

- We acknowledge Tribes as sovereign nations that have a government-to-government relationship with the United States. Sovereignty is inherent to Tribes; it is not something we or others can give or take away.

- We will not be ashamed to say, “I know not,” nor will we fail to call in our colleagues when the skills of another are needed for solving a problem.

- We will respect the privacy of those who provide any data, for their data are not disclosed to us that the world may know, so we will tread with care in matters of privacy and security.

- We will remember that data are not just numbers without meaning or context, but represent real people and situations, and that working with data may lead to unintended societal consequences, such as inequality, poverty, and disparities due to algorithmic bias.



## Principles for effective collaboration and consulting

During ongoing training, we will demo short lessons or consulting scenarios as through microteaching, sharing feedback on what makes the lesson/exchange effective and what would make it more effective.

We will discuss common pitfalls and how to avoid them.


## Resources

We will cover some of these as a group in our ongoing training, and you can also explore them yourselves.

- Darren Ranco and Dean Suagee (2007), [Tribal Sovereignty and the Problem of Difference in Environmental Regulation: Observations on "Measured Separatism" in Indian Country.](https://drive.google.com/file/d/1SO_rzZfOmiyAmYnkKNjTfQpAq8Qv60RA/view) [*Antipode*](https://onlinelibrary.wiley.com/journal/14678330).

- [Indian Country 101](https://www.conservationtraining.org/course/view.php?id=309) Tutorial

- [CARE principles for Indigenous Data Governance](https://www.gida-global.org/care)

- Maggie Walter and Chris Anderson (2016), [Indigenous Statistics: A Quantitative Research Methodology.](https://www.taylorfrancis.com/books/oa-mono/10.4324/9781315426570/indigenous-statistics-maggie-walter-chris-andersen) (open-source text)

- [Data science ethics](https://mdsr-book.github.io/mdsr3e/08-ethics.html) (Chapter 8 of Modern Data Science with R, 3rd ed., by Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton)

- Wilkinson, Charles F. (2024). Treaty justice: the Northwest Tribes, the Boldt Decision, and the Recognition of Fishing Rights. University of Washington Press. [Available through UW Library here.](https://orbiscascade-washington.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma99162774763301452&context=L&vid=01ALLIANCE_UW:UW&lang=en&search_scope=UW_EVERYTHING&adaptor=Local%20Search%20Engine&tab=UW_default&query=any,contains,treaty%20justice)

- Dover, Harriette S. (2013). Tulalip, From My Heart: An Autobiographical Account of a Reservation Community (1st ed.). University of Washington Press. [Available through UW Library here.](https://orbiscascade-washington.primo.exlibrisgroup.com/discovery/fulldisplay?docid=cdi_askewsholts_vlebooks_9780295804934&context=PC&vid=01ALLIANCE_UW:UW&lang=en&search_scope=UW_EVERYTHING&adaptor=Primo%20Central&tab=UW_default&query=any,contains,tulalip&offset=0)



